config/routes.rb
Rails.application.routes.draw do
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]
  get '/favorites/id', to: 'users#favorite'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  mount_uploader :profile_image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

   def authenticate_user
    if @current_user == nil
        flash[:notice] = t('notice.login_needed')
        redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :update, :edit, :destroy, :current_user]

  def index
    @pictures = Picture.all
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    @picture = Picture.new
  end

  def edit
    if @picture.user_id == current_user.id
    else
      redirect_to user_path(current_user.id)
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
        PictureMailer.picture_mail(@picture).deliver
        #redirect_to pictures_path, notice: 'Picture was successfully created.'
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to new_session_path
      else
        render :new
      end
  end

  def show
    if current_user.id != @user.id
    redirect_to user_path(current_user.id)
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(update_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def favorite
    @favorites = Favorite.where(params[:id])
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1>お気に入りした画像一覧</h1>

<tbody>
  <% @favorites.each do |favorite| %>
    <tr>
      <td><%= image_tag favorite.favorite_users %></td>
      <td><%= favorite.content %></td>
      <td><%= favorite.user.name %></td>
      <td><%= link_to 'Show', picture %></td>
      <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
      <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloneI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<header>
    <body class="application_body">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <button class="application_button"><%= link_to "プロフィール", user_path(current_user.id) %></button>
      <button class="application_button"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></button>
    <% else %>
      <button class="application_button"><%= link_to "サインアップ", new_user_path %></button>
      <button class="application_button"><%= link_to "ログイン", new_session_path %></button>
    <% end %>
    <%= yield %>
  </body>
</header>

<footer>
</footer>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image, "画像" %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :content, "内容" %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <p class="picture_new_action"><%= form.submit %></p>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3 class="picture_confirm_h3">以下の内容で、送信する。</h3>
<%= form_with(model: @picture, local: true) do |form| %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @picture.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h1 class="picture_edit_h1">投稿を編集</h1>

<%= render 'form', picture: @picture %>

<button><%= link_to '詳細', @picture %></button>
<button><%= link_to '戻る', pictures_path %></button>

app/views/pictures/index.html.erb
<h1 class="picture_index_h1">投稿一覧</h1>
<p id="notice"><%= notice %></p>

<table class="picture_index_table">
  <thead>
    <tr>
      <th class="picture_index_th">画像</th>
      <th class="picture_index_th">内容</th>
      <th class="picture_index_th">投稿者</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td class="picuture_index_td"><%= image_tag picture.image.url %></td>
        <td class="picuture_index_td"><%= picture.content %></td>
        <td class="picuture_index_td"><%= picture.user.name %></td>
        <td><button class="picture_index_button"><%= link_to '詳細', picture %></button></td>
        <% if current_user.id == picture.user_id %>
        <td><button class="picture_index_button"><%= link_to '編集', edit_picture_path(picture) %></button></td>
        <td><button class="picture_index_button"><%= link_to '削除', picture, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<p><button><%= link_to '新規投稿', new_picture_path %></button></p>

app/views/pictures/new.html.erb
<h1 class="picture_new_h1">新規投稿</h1>

<%= render 'form', picture: @picture %>

<button><%= link_to '投稿一覧', pictures_path %></button>

app/views/pictures/show.html.erb
<p class="picture_show_p1">
  <%= image_tag @picture.image.url %>
</p>

<p>
  <strong>内容:</strong>
  <%= @picture.content %>
</p>

<p>
  <strong>投稿者:</strong>
  <%= @picture.user.name %>
</p>

<div>
<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
</div>

<button><%= link_to '投稿一覧', pictures_path %></button>
<% if current_user.id == @picture.user_id %>
  <button><%= link_to '編集', edit_picture_path(@picture) %></button>
<% end %>

app/views/users/_form.html.erb
<div class="album_new_body">
　　<h1>ユーザー登録</h1>
　　<%= form_with(model: user, local: true) do |form| %>
      <% if user.errors.any? %>
　　　　  <div id="error_explanation">
      　　  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      　　  <ul>
      　　  <% user.errors.full_messages.each do |message| %>
        　　  　<li><%= message %></li>
      　　  <% end %>
      　　</ul>
　　　　</div>
      <% end %>

  <table class="form_new_table">
    <tr>
      <th><%= form.label :name, "名前" %></th>
      <th><%= form.text_field :name %></th>
    </tr>

    <tr class="field">
      <th><%= form.label :email, "メールアドレス" %></th>
      <th><%= form.text_field :email %></th>
    </tr>

    <tr class="field">
      <th><%= form.label :password, "パスワード" %></th>
      <th><%= form.password_field :password %></th>
    </tr>

    <tr class="field">
      <th><%= form.label :password_confirmation, "確認用パスワード" %></th>
      <th><%= form.password_field :password_confirmation %></th>
    </tr>

    <tr>
      <th></th>
      <th id="make_account"><%= form.submit %><th>
    </tr>
  <% end %>
  </table>
</div>

app/views/users/edit.html.erb
<body class="users_edit_body">
  <%= form_with(model: @user, local: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <h1 class="users_edit_h1">プロフィール編集</h1>
  <div class="users_edit_div">
    <table class="field">
      <tr>
        <th><%= form.label :name %></th>
        <th><%= form.text_field :name %></th>
      </tr>
      <tr>
      <th><%= form.label :email %></th>
      <th><%= form.text_field :email %></th>
      </tr>
      <tr>
        <th><%= form.label :password %></th>
        <th><%= form.text_field :password %></th>
      </tr>
      <tr>
        <th><%= form.label :password_confirmation %></th>
        <th><%= form.text_field :password_confirmation %></th>
      </tr>
      <tr>
        <th><%= form.label :profile_image, "プロフィール写真" %></th>
        <th><%= form.file_field :profile_image %></th>
      </tr>

      <tr class="actions">
        <th></th>
        <th><%= form.submit %></th>
      </tr>
    </table>
  <% end %>

  <div class="user_edit_button">
    <button><%= link_to "投稿一覧", pictures_path %></button>
  </div>
</body>

app/views/users/favorite.html.erb
<h1 class="users_favorite_h1">お気に入りした画像</h1>

<tbody>
  <% @favorites.each do |favorite| %>
    <p　class="users_favorite_td"><%= image_tag favorite.picture.image.url %></p>
  <% end %>
</tbody>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1 class="users_show_h1"><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>

<% if @user.profile_image.present? %>
  <%= image_tag @user.profile_image.url %>
<% else %>
  <p>プロフィール画像を登録してください。</p>
<% end %>

<div class="profile_button">
  <% if current_user.id == @user.id %>
    <button><%= link_to 'プロフィール編集', edit_user_path %></button>
    <button><%= link_to "お気に入り一覧", favorites_id_path %></button>
    <button><%= link_to '投稿一覧', pictures_path %></button>
    <button><%= link_to "新規投稿", new_picture_path %></button>
  <% end %>
</div>